#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
import re
import os
import json
import subprocess
import requests

from pathlib import Path

from myfunc import media

from myfunc.util import tr_add_torrent, get_apikey

s = requests.Session()
login = s.post('https://fsm.name/Users/loginSubmit', data={'username': get_apikey('fsm_username'), 'password': get_apikey('fsm_passwd')})
print(login.json())

def upload_image(content: 'bytes'):
    return s.post("https://fsm.name/PicUpload/upload", files={'file': ('image.png', content)}).json()['data']['url']

p = Path(sys.argv[1])
mp4_file = next(i for i in p.iterdir() if i.suffix == '.mp4')

if re.match('[A-Z]+-\d+', p.name):
    info = requests.get(f"https://oracle.tomyangsh.pw/api/dmm?keyword={p.name}").json()[0]
    title = f"{info['pid']} {info['name']}"
    tags = None
    content = f"<p><img src={info['poster']}></p>"
    upload_type = 1
    filename_new = p.name + '.mp4'
else:
    upload_type = 7
    name_parse = re.match('(\w+)\.(\d\d\.\d\d\.\d\d|E\d+)\.(.+?)\.XXX', p.name)
    site = name_parse.group(1)
    date = f"{name_parse.group(2)}"
    title_list = name_parse.group(3).replace('.And', ',').split('.')
    print(title_list)
    insert_index = int(input('分隔符位置: '))
    if insert_index == 0:
        actor_list = []
    elif insert_index == len(title_list):
        actor_parse = re.findall('[\w\s]+', ' '.join(title_list))
        actor_list = [i.strip() for i in actor_parse]
    else:
        title_list.insert(insert_index, '-')
        actor_parse = re.findall('[\w\s]+', ' '.join(title_list[0:insert_index]))
        actor_list = [i.strip() for i in actor_parse]
    tag_list = [site] + actor_list
    tags = ','.join(tag_list)
    title = f"[{site}] {' '.join(title_list)} -- {date} [1080p]"
    filename_new = re.match('(.+?)MP4', p.name).group(1) + 'mp4'

    thumb = []
    for i in [3, 6, 9, 12, 15, 18]:
        try:
            f = media.screenshot(mp4_file, f'{i}:00')
            if len(f):
                thumb.append(upload_image(f))
        except:
            continue
    content = '<p><img src="'+'"><img src="'.join(thumb)+'"></p>'

if not Path(filename_new).is_file():
    os.link(mp4_file, filename_new)

torrent_name = filename_new + '.torrent'
if not Path(torrent_name).is_file():
    subprocess.run(['transmission-create', '-p', '-s', '4096', '-t', f"https://creditracker.net/Announce?passkey={get_apikey('fsm_passkey')}", '-r', 'FSM', filename_new])

upload_form = {
        'type': upload_type,
        'title': title,
        'tags': tags,
        'content': content,
        'torrentFile': open(torrent_name, 'rb')
        }

upload_res = s.post('https://fsm.name/Torrents/newSubmit', data=upload_form, files={'torrentFile': open(torrent_name, 'rb')}).json()
print(upload_res['msg'])
logout = s.post('https://fsm.name/Users/logout')

if upload_res['success']:
    torrent_file = Path(torrent_name)
    tr_add_torrent(str(torrent_file.absolute()))
    torrent_file.unlink()
