#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
import re
import requests
import webbrowser
import subprocess
import os

from pathlib import Path

from mutagen.flac import FLAC

from myfunc import media
from myfunc.util import get_apikey, tr_add_torrent

p = Path(sys.argv[1])
nfo = open(next(i for i in p.iterdir() if i.suffix == '.nfo'), errors='ignore').read()

artist = re.search('Artist\.*:\s*(.*?)\|', nfo).group(1).strip()
title = re.search('Album\.*:\s*(.*?)\|', nfo).group(1).strip()
genre = re.sub(' ', '.', re.search('Genre\.*:\s*(.*?)\|', nfo).group(1).strip().lower())
label = re.search('Label\.*:\s*(.*?)\|', nfo).group(1).strip()
year = re.search('Year\.*:\s*(.*?)\|', nfo).group(1).strip()
catalogue_number = re.search('Cat\.No\.*:\s*(.*?)\|', nfo).group(1).strip()
source = re.search('Source\.*:\s*(.*?)\|', nfo).group(1).strip()

if re.search('WEB', source):
    media_type = 'WEB'
elif re.search('CD', source):
    media_type = 'CD'
    webbrowser.open(f"https://www.google.com/search?q={artist} {title}")
    iamge = input('image: ')

if re.search('EP', source):
    release_type = 5
else:
    release_type = 1

if re.search('24bit', source):
    bitrate = '24bit Lossless'
else:
    bitrate = 'Lossless'

desc = 'Tracklist:\n\n'
desc += '\n'.join(re.sub('(\d\d?:\d\d)', r'(\1)', i) for i in re.findall('0\d\.\s.+\d:\d\d', nfo))

dir_parse = re.match('(\w+)-(\w+)', sys.argv[1])
dir_new = f"{re.sub('_', ' ', dir_parse.group(1))} - {re.sub('_', ' ', dir_parse.group(2))} ({year}) [{media_type} FLAC]"
os.mkdir(dir_new)

for i in p.iterdir():
    if i.suffix == '.jpg' and media_type == 'WEB':
        os.link(i, f"{dir_new}/cover.jpg")
        image = media.upload_image(open(i, 'rb'), 'imgur')
    elif i.suffix == '.flac':
        song = FLAC(i)
        song_title = song.tags.get('TITLE')[0]
        song_tracknumber = song.tags.get('TRACKNUMBER')[0]
        filename_new = f"{song_tracknumber}. {song_title}.flac"
        os.link(i, f"{dir_new}/{filename_new}")

subprocess.run(['transmission-create', '-p', '-s', '4096', '-t', f"https://home.opsfet.ch/{get_apikey('ops_passkey')}/announce", '-r', 'OPS', dir_new])
torrent_name = dir_new + '.torrent'

upload_arguments = {
            "type": 0,
            "artists[0]": artist,
            "importance[0]": 1,
            "title": title,
            "year": year,
            "record_label": label,
            "releasetype": release_type,
            "media": media_type,
            "format": 'FLAC',
            "bitrate": bitrate,
            "tags": genre,
            "image": image,
            "album_desc": desc
        }

upload_res = requests.post('https://orpheus.network/ajax.php?action=upload', headers={'Authorization': get_apikey('ops')}, data=upload_arguments, files={'file_input': open(torrent_name, 'rb')}).json()

print(upload_res)
if upload_res['status'] == 'success':
    torrent_file = Path(torrent_name)
    tr_add_torrent(str(torrent_file.absolute()))
    torrent_file.unlink()
