#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
import re
import requests
import subprocess
import os

from pathlib import Path
from datetime import timedelta

from mutagen.flac import FLAC

from myfunc import media
from myfunc.util import get_apikey, tr_add_torrent

p = Path(sys.argv[1])
nfo = next(p.glob('*.nfo')).read_text(errors='ignore')
flac = FLAC(next(p.glob('*.flac')))

artist = flac.get('ARTIST')[0]
title = flac.get('ALBUM')[0]
genre = re.sub(' ', '.', flac.get('GENRE')[0].lower())
year = flac.get('DATE')[0]
label = re.search('label[^\w\n]+([\w ]*)', nfo, re.I).group(1).strip()

media_type = 'WEB'

if re.search('EP', p.name):
    release_type = 5
else:
    release_type = 1

if re.search('24BIT', p.name):
    bitrate = '24bit Lossless'
else:
    bitrate = 'Lossless'

desc = 'Tracklist:\n\n'

dir_new = f"{artist} - {title} ({year}) [WEB FLAC]"
os.mkdir(dir_new)

image = ''

for i in sorted(p.iterdir()):
    if i.suffix == '.jpg':
        os.link(i, f"{dir_new}/cover.jpg")
        image = media.upload_image(open(i, 'rb'), 'imgur')
    elif i.suffix == '.flac':
        song = FLAC(i)
        song_title = song.tags.get('TITLE')[0]
        song_tracknumber = song.tags.get('TRACKNUMBER')[0]
        filename_new = f"{song_tracknumber}. {song_title}.flac"
        os.link(i, f"{dir_new}/{filename_new}")
        desc += f"{song.get('TRACKNUMBER')[0].zfill(2)}. {song.get('TITLE')[0]} ({str(timedelta(seconds=round(song.info.length)))[-5:]})\n"

if not image:
    image = input('image: ')

subprocess.run(['transmission-create', '-p', '-s', '4096', '-t', f"https://home.opsfet.ch/{get_apikey('ops_passkey')}/announce", '-r', 'OPS', dir_new])
torrent_name = dir_new + '.torrent'

upload_arguments = {
            "type": 0,
            "artists[0]": artist,
            "importance[0]": 1,
            "title": title,
            "year": year,
            "record_label": label,
            "releasetype": release_type,
            "media": media_type,
            "format": 'FLAC',
            "bitrate": bitrate,
            "tags": genre,
            "image": image,
            "album_desc": desc
        }

upload_res = requests.post('https://orpheus.network/ajax.php?action=upload', headers={'Authorization': get_apikey('ops')}, data=upload_arguments, files={'file_input': open(torrent_name, 'rb')}).json()

print(upload_res)
if upload_res['status'] == 'success':
    torrent_file = Path(torrent_name)
    tr_add_torrent(str(torrent_file.absolute()))
    torrent_file.unlink()
