#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
import os
import subprocess
import re
import json
import ffmpeg
import requests
import webbrowser

from tmdb import method, type
from myfunc import media

file_path = sys.argv[1]
file_name = os.path.basename(file_path)

mediainfo = media.mediainfo(file_path)

thumb = []

try:
    for i in [3, 6, 9, 12]:
        f = media.ss(file_path, f'{i}:00')
        thumb.append(media.upload(f))
    thumb = '[img]'+'[/img]\n[img]'.join(thumb)+'[/img]'
except Exception as e:
    pass

query = re.match('(.+)\.((\d){4}\.|(\w\d\d){2})', file_name).group(1)
query = re.sub('\.', ' ', query)
search = requests.get(f'https://oracle.tomyangsh.pw/ptinfo/api/search?query={query}').json()
if search:
    print('\n'.join(f"{search.index(i)}. {i['cat']} {i['name']} {i.get('date')}" for i in search[:5]))
    choice = int(input())
    choice = search[choice]

detail = requests.get('https://oracle.tomyangsh.pw/ptinfo/api/detail', params=choice).json()

if detail['cat'] == 'movie':
    des = f"""{detail['info']}
{thumb}

[expand]
{mediainfo}
[/expand]"""

    dic = {'cat': '419', 'name': detail['zh_names'], 'imdb': detail['imdb'], 'code': '1', 'res': '1', 'area': '2', 'des': des}

if detail['cat'] == 'tv':
    print('\n'.join(f"{detail['poster'].index(i)}. {i['name']}" for i in detail['poster']))
    choice = int(input())
    poster = detail['poster'][choice]['path']
    des = f"""[img]{poster}[/img]
{detail['info']}
{thumb}

[expand]
{mediainfo}
[/expand]"""

    dic = {'cat': '402', 'name': detail['zh_names'], 'imdb': detail['imdb'], 'code': '1', 'res': '1', 'area': '2', 'des': des}

json_url = requests.post('https://fars.ee/', files={'file': json.dumps(dic, ensure_ascii=False)}).text
json_url = re.search('url: (.+)\\n', json_url).group(1)
webbrowser.open('https://kp.m-team.cc/upload.php#info='+json_url)

