#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
import os
import subprocess
import re
import json
import ffmpeg
import requests
import webbrowser
import cn2an

from tmdb import method, type
from myfunc import media

file_path = sys.argv[1]
file_name = os.path.basename(file_path)

mediainfo = media.mediainfo(file_path)
zhsub = media.Video(file_path).zhsub

thumb = []

try:
    for i in [3, 6, 9, 12]:
        f = media.ss(file_path, f'{i}:00')
        thumb.append(media.upload(f))
    thumb = '[img]'+'[/img]\n[img]'.join(thumb)+'[/img]'
except Exception as e:
    pass

parse = re.match('(.+)\.((\d){4}\.|(\w\d\d){2})', file_name)
query = re.sub('\.', ' ', parse.group(1))
search = requests.get(f'https://oracle.tomyangsh.pw/ptinfo/api/search?query={query}').json()
if search:
    print('\n'.join(f"{search.index(i)}. {i['cat']} {i['name']} {i.get('date')}" for i in search[:5]))
    choice = int(input())
    if choice in range(0, 5):
        choice = search[choice]
    else:
        choice = {'id': choice, 'cat': input('cat: ')}
else:
    choice = {'id': input('id: '), 'cat': input('cat: ')}

detail = requests.get('https://oracle.tomyangsh.pw/ptinfo/api/detail', params=choice).json()

if detail['cat'] == 'movie':
    des = f"""{detail['info']}
{thumb}

[expand]
{mediainfo}
[/expand]"""

    dic = {'cat': '419', 'name': detail['zh_names'], 'imdb': detail['imdb'], 'code': '1', 'res': '1', 'area': '2', 'des': des, 'zhsub': zhsub}

if detail['cat'] == 'tv':
    parse_ep = re.findall('\d+', parse.group(2))
    season = cn2an.an2cn(parse_ep[0])
    ep = parse_ep[1].lstrip('0')
    name = f"{detail['zh_names']} 第{season}季 第{ep}集"
    print('\n'.join(f"{detail['poster'].index(i)}. {i['name']}" for i in detail['poster']))
    choice = int(input())
    poster = detail['poster'][choice]['path']
    des = f"""[img]{poster}[/img]
{detail['info']}
{thumb}

[expand]
{mediainfo}
[/expand]"""

    dic = {'cat': '402', 'name': name, 'imdb': detail['imdb'], 'code': '1', 'res': '1', 'area': '2', 'des': des, 'zhsub': zhsub}

forminfo_id = requests.post('https://oracle.tomyangsh.pw/ptinfo/api/forminfo', json=dic).text
forminfo_url = f"https://oracle.tomyangsh.pw/ptinfo/api/forminfo?id={forminfo_id}"
webbrowser.open('https://kp.m-team.cc/upload.php#info='+forminfo_url)

