#!/usr/bin/python

import sys
import os
import requests
import re

from myfunc import tg, media, util

def get_metadata(video_path):
    width, height, duration = 1920, 1080, 0
    try:
        video = media.Video(video_path)
        height = video.height
        width = video.width
        duration = video.duration
    except Exception as e:
        print(e)
    return dict(height=height, width=width, duration=duration)

def progress(current, total):
    sys.stdout.write(f"\r{current * 100 / total:.1f}%")
    sys.stdout.flush()

with tg.client() as app:
    video_path = sys.argv[1]
    if len(sys.argv) == 2:
        video_name = os.path.basename(video_path)
        ep_no = re.search('\w\d\d\w\d\d', video_name).group().upper()
        query = re.sub('\.', ' ', re.match('(.+?)\.((\d){4}\.)?\w\d\d\w\d\d', video_name).group(1))
        res = requests.get(f'https://tomyangsh.pw/api/tmdb?keyword={query}').json()
        if res:
            res = res[0]
            name_chi = re.sub('：', '_', res.get('name'))
            name_org = re.sub('：', '_', res.get('ori_name'))
            thumbnail = util.bytesio(requests.get(res.get('backdrop')).content, 'jpg')
            caption = '#'+name_chi+' '+name_org+' '+ep_no
            print(caption)
        else:
            caption = video_name
            thumbnail = None
    else:
        caption = sys.argv[2]
        thumbnail = None
    meta = get_metadata(video_path)
    app.send_video("me", video_path, caption=caption, thumb=thumbnail, **meta, progress=progress)
